#!/usr/bin/python3 -i

# This file is part of the Home2L project.
#
# (C) 2015-2021 Gundolf Kiefer
#
# Home2L is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Home2L is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Home2L. If not, see <https://www.gnu.org/licenses/>.


# Testbench for testing new features of the Python API.

from home2l import *

import os




print ("### Init...")
Home2lInit ("test-rulesapi", True)
    # Init Home2l-Resources: Pass full instance name and enable the server





############################## Driver definitions ##############################


NewResource ("pytest", "pyInt", rctInt, True)   # writeable resource

@driver ("pytest", rcsBusy)
def DrivePytest (rc, vs):
  print ("DrivePytest: ", vs, " -> ", rc)
  rc.ReportValueState (vs)      # ", rcsValid" is not necessary





############################## Rules ###########################################


@onUpdate ("/local/timer/now")
def PrintTime ():
  #~ print ("###", rc, "#", vs.ToStr (True), "#")
  #~ print ("# type = ", vs.Type ())
  #~ print ("# value = ", vs.Value ())
  vs = RcGet ("/local/timer/now").ValueState ()
  print ("The time is: " + vs.ToStr ())
  #~ try:
    #~ tRec = CRcTime (vs.Value () * 1000)
  #~ except (AttributeError, TypeError):
    #~ print ("The time is unknown.")
  #~ else:
    #~ if tRec.ts % 10 == 3:
      #~ print ("  -> requesting testInt...")
      #~ RcSetRequest ("/host/lilienthal/signal/testInt", "timer", tRec.ts)
    #~ if tRec.ts % 5 == 3:
      #~ print ("  -> requesting testFloat...")
      #~ RcSetRequest ("/host/lilienthal/signal/testFloat", "timer", tRec.ts / 10.0)


@onEvent ([ "/host/lilienthal/signal/testInt", "/host/lilienthal/signal/testFloat", "/local/pytest/*" ])
def TestEvents (evType, rc, vs):
  #~ if not rc: return [ "/host/lilienthal/signal/testInt", "/host/lilienthal/signal/testFloat", "/local/pytest/*" ]
  print ("Event:", CRcEvent (evType, rc, vs))



##### Timer #####


@at (TicksOfSeconds (0.5))
def TimerSoon ():
  print ("Timer 1: soon")

@at (1500)
def TimerLater ():
  print ("Timer 2: later")
  RcSetRequest ("/local/pytest/pyInt", 42, id = "timer")

@at (dt = TicksOfSeconds (3.5))
def TimerOften ():
  print ("Timer 3: often")



def TimerWithData (data):
  print ("Timer 4: data = '" + data + "'")

RunAt (TimerWithData, TicksNow () + TicksOfSeconds (2), 0, "my data")



############################## Random Sensors ##################################

# TBD: Update (was from previous showhouse)

#~ rcSensor1 = RcDefResource ("showhouse", "sensor1", rctBool, False)   # read-only resource
#~ rcSensor2 = RcDefResource ("showhouse", "sensor2", rctBool, False)   # read-only resource
#~ rcSensor3 = RcDefResource ("showhouse", "sensor3", rctBool, False)   # read-only resource
#~ rcSensor4 = RcDefResource ("showhouse", "sensor4", rctBool, False)   # read-only resource


#~ drvCounter = 0

#~ def IterateDrivers (data):
  #~ global drvCounter
  #~ rcSensor1.ReportValue (drvCounter % 2);
  #~ rcSensor2.ReportValue ((drvCounter // 2) % 2);
  #~ rcSensor3.ReportValue ((drvCounter // 3) % 2);
  #~ rcSensor4.ReportValue ((drvCounter // 4) % 2);
  #~ drvCounter += 1

#~ RcRunAt (IterateDrivers, 0, 1000)








############################## Go ahead ########################################

print ("### Run...")

Home2lRun ()           # Run main event loop...
Home2lDone ()          # Shutdown Home2l-Resources (sometimes we never get here)
