#!/bin/bash

# This file is part of the Home2L project.
#
# (C) 2015-2021 Gundolf Kiefer
#
# Home2L is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Home2L is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Home2L. If not, see <https://www.gnu.org/licenses/>.





############################# Helper functions #################################


usage () {
  echo "Usage: ${0##*/} [-e] [-b] [-a] [<host 1> <host 2> ...]"
  echo "  -e | --etc:   Update the configuration data on all (selected) hosts"
  echo "  -b | --blob:  Update the big blob on all (selected) hosts"
  echo "  -a | --apk:   (Re-)Install the Android app on all (selected) Android hosts"
  echo "  -m:           Do not update data on Android master"
  echo "  -y:           Do not ask for confirmation"
  echo
  echo "If none of -e, -b and -a are given, everything is updated."
  echo "If no host is given, all known hosts are updated."
  echo
  echo "Note: For each new Android device, the app has to be installed first and"
  echo "      run once before its configuration data can be uploaded."
}


error () {
  echo "$1"
  echo
  usage
  exit
}


banner () {
  echo
  echo
  echo
  echo "######################################################################"
  echo "#"
  echo "#   $1"
  echo "#"
  echo "######################################################################"
  echo
}


intersect () {
  RET=""
  for X in $1; do
    for Y in $2; do
      if [[ "$X" == "$Y" ]]; then
        RET="$RET $X"
      fi
    done
  done
  echo $RET
}


without () {
  RET=""
  for X in $1; do
    HIT=0
    for Y in $2 $RET; do
      #~ echo "### X='"$X"' Y='"$Y"' RET='"$RET"'"
      if [[ "$X" == "$Y" ]]; then
        HIT=1
      fi
    done
    if [[ $HIT == 0 ]]; then
      RET="$RET $X"
      #~ echo "### RET='"$RET"'"
    fi
  done
  echo $RET
}





############################# Preparation ######################################


# Read configuration & do some sanity checks...
set -e
CONF=$HOME2L_ROOT/etc/rollout.conf
test -e $CONF || error "Cannot find configuration file $CONF"
. $CONF
if [[ "$HOSTNAME" != "$MASTER" ]]; then
  exec ssh -t $MASTER home2l ${0##*-} $@
fi


# Evaluate command line...
DO_ETC=0
DO_BLOB=0
DO_APK=0
DO_MASTER=1
ASK_CONFIRM=1
HOSTS=""
for ARG in $@; do
  case $ARG in
    -h | --help)
      usage
      exit 0
      ;;
    -e | --etc)
      DO_ETC=1
      ;;
    -b | --blob)
      DO_BLOB=1
      ;;
    -a | --apk)
      DO_APK=1
      ;;
    -m)
      DO_MASTER=0
      ;;
    -y)
      ASK_CONFIRM=0
      ;;
    *)
      HOSTS="$HOSTS $ARG"
      ;;
  esac
done
if [[ $DO_ETC == 0 && $DO_BLOB == 0 && $DO_APK == 0 ]]; then
  DO_ETC=1
  DO_BLOB=1
  DO_APK=1
fi


# Filter hosts...
if [[ "$HOSTS" == "" ]]; then
  SEL_LINUX="$HOSTS_LINUX"
  SEL_LINUX_NOETC="$HOSTS_LINUX_NOETC"
  SEL_ANDROID="$HOSTS_ANDROID"
else
  SEL_LINUX=`intersect "$HOSTS" "$HOSTS_LINUX"`
  SEL_LINUX_NOETC=`intersect "$HOSTS" "$HOSTS_LINUX_NOETC"`
  SEL_ANDROID=`intersect "$HOSTS" "$HOSTS_ANDROID"`
fi
if [[ $DO_ETC == 1 ]]; then
  SEL_ETC="$SEL_LINUX $SEL_ANDROID"
else
  SEL_ETC=""
fi
if [[ $DO_BLOB == 1 ]]; then
  SEL_BLOB="$SEL_LINUX $SEL_LINUX_NOETC"
else
  SEL_BLOB=""
fi
if [[ $DO_APK == 1 ]]; then
  SEL_APK="$SEL_ANDROID"
else
  SEL_APK=""
fi


# Determine indirect updates for Android masters...
SEL_APK_MASTERS=""
if [[ $DO_MASTER == 1 ]]; then
  if [[ "$SEL_APK" != "" ]]; then
    SEL_APK_MASTERS=`without "$ANDROID_MASTERS" "$SEL_BLOB"`
  fi
  if [[ `intersect "$SEL_ETC" "$HOSTS_ANDROID"` != ""  ]]; then
    NEW_ETC=`without "$ANDROID_MASTERS" "$SEL_ETC"`
    SEL_ETC="$NEW_ETC $SEL_ETC"
  fi
fi


# Optimize blob/etc and apk/etc...
SEL_BLOB_AND_ETC=`intersect "$SEL_BLOB" "$SEL_ETC"`
SEL_BLOB=`without "$SEL_BLOB" "$SEL_BLOB_AND_ETC"`
SEL_ETC=`without "$SEL_ETC" "$SEL_BLOB_AND_ETC"`

SEL_APK_AND_ETC=`intersect "$SEL_APK" "$SEL_ETC"`
SEL_APK=`without "$SEL_APK" "$SEL_APK_AND_ETC"`
SEL_ETC=`without "$SEL_ETC" "$SEL_APK_AND_ETC"`



# "Are you sure"?
if [[ "$ASK_CONFIRM" == 1 ]]; then
  echo "You selected to do the following:"
  if [[ "$SEL_BLOB_AND_ETC" ]]; then
    echo "- Update blob and configuration on: $SEL_BLOB_AND_ETC"
  fi
  if [[ "$SEL_BLOB" != "" ]]; then
    echo "- Update the big blob on:           $SEL_BLOB"
  fi
  if [[ "$SEL_ETC" != "" ]]; then
    echo "- Update configuration files on:    $SEL_ETC"
  fi
  if [[ "$SEL_APK_MASTERS" != "" ]]; then
    echo "- Update 'Home2lApp.apk' on:        $SEL_APK_MASTERS"
  fi
  if [[ "$SEL_APK_AND_ETC" != "" ]]; then
    echo "- Update Android app + config on:   $SEL_APK_AND_ETC"
  fi
  if [[ "$SEL_APK" != "" ]]; then
    echo "- Update Android app on:            $SEL_APK"
  fi
  echo
  echo "All data will be replicated from: $MASTER:$HOME2L_ROOT"
  echo
  read -p "Continue? (y/N) " ANS
  if [[ "$ANS" != "y" ]]; then
    exit
  fi
fi





############################# Update Linux Hosts ###############################


# Rollout blob + etc...
for HOST in $SEL_BLOB_AND_ETC; do
  banner "Updating blob and configuration on '$HOST' ..."
  ssh $HOST home2l install -b -e home2l@$MASTER:$HOME2L_ROOT
done


# Rollout blob ...
for HOST in $SEL_BLOB; do
  banner "Updating the big blob on '$HOST' ..."
  ssh $HOST home2l install -b home2l@$MASTER:$HOME2L_ROOT
done


# Rollout etc (Linux) ...
for HOST in `intersect "$SEL_ETC" "$HOSTS_LINUX"`; do
  banner "Updating configuration files on '$HOST' ..."
  ssh $HOST home2l install -e home2l@$MASTER:$HOME2L_ROOT
done


# Rollout APK file only ...
for HOST in $SEL_APK_MASTERS; do
  banner "Updating 'Home2lApp.apk' on '$HOST' ..."
  ssh $HOST home2l install -a home2l@$MASTER:$HOME2L_ROOT
done





############################# Update Android Hosts #############################


# Rollout Android app + etc ...
for HOST in $SEL_APK_AND_ETC; do
  banner "Updating the Android app + etc on '$HOST' ..."
  home2l adb $HOST x-install-etc
  home2l adb $HOST x-install-apk
  home2l adb $HOST x-restart
    # Note: HOME2L_ROOT must be equivalent on all Android masters
done


# Rollout Android app ...
for HOST in $SEL_APK; do
  banner "Updating the Android app on '$HOST' ..."
  home2l adb $HOST x-install-apk
  home2l adb $HOST x-start
    # Note: HOME2L_ROOT must be equivalent on all Android masters
done


# Rollout etc (Android) ...
for HOST in `intersect "$SEL_ETC" "$HOSTS_ANDROID"`; do
  banner "Updating configuration files on '$HOST' ..."
  home2l adb $HOST x-install-etc
  home2l adb $HOST x-restart
done
